apiVersion: v1
kind: Service
metadata:
  name: basketdata
  namespace: eshop-data
  labels:
    app.kubernetes.io/name: basketdata
    app.kubernetes.io/part-of: eshop
    tier: data
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: basketdata
  ports:
  - name: p6379
    port: 6379
    targetPort: 6379
