apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: eshop-apis
  labels:
    app.kubernetes.io/name: catalog-api
    app.kubernetes.io/part-of: eshop
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog-api
        app.kubernetes.io/part-of: eshop
        tier: api
    spec:
      serviceAccountName: eshop-developer
      containers:
      - name: catalog-api
        image: azw7225/catalog-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 81
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__CatalogDb
          valueFrom:
            secretKeyRef:
              name: secret
              key: ConnectionStrings__CatalogDb
        - name: PicBaseUrl
          value: http://docker.internal.localhost:5202/c/api/v1/catalog/items/[0]/pic/
        - name: EventBusConnection
          value: rabbitmq.eshop-data.svc.cluster.local
        - name: UseCustomizationData
          value: "True"
        - name: AzureServiceBusEnabled
          value: "False"
        - name: AzureStorageEnabled
          value: "False"
        - name: GRPC_PORT
          value: "81"
        - name: PORT
          value: "80"
        - name: PATH_BASE
          value: /catalog-api
        envFrom:
          - configMapRef:
              name: external-links
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        # Temporarily disabled for autoscaling demo
        # livenessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
