apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: eshop-apis
  labels:
    app.kubernetes.io/name: identity-api
    app.kubernetes.io/part-of: eshop
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: identity-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: identity-api
        app.kubernetes.io/part-of: eshop
    spec:
      serviceAccountName: eshop-developer
      containers:
      - name: identity-api
        image: azw7225/identity-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: SpaClient
          value: http://docker.internal.localhost:5104
        - name: XamarinCallback
          value: http://10.121.122.162:5105/xamarincallback
        - name: ConnectionString
          value: Server=sqldata.eshop-data.svc.cluster.local;Database=Microsoft.eShopOnContainers.Service.IdentityDb;User Id=sa;Password=Pass@word
        - name: MvcClient
          value: http://docker.internal.localhost:5100
        - name: BasketApiClient
          value: http://docker.internal.localhost:5103
        - name: OrderingApiClient
          value: http://docker.internal.localhost:5102
        - name: MobileShoppingAggClient
          value: http://docker.internal.localhost:5120
        - name: WebShoppingAggClient
          value: http://docker.internal.localhost:5121
        - name: WebhooksApiClient
          value: http://docker.internal.localhost:5113
        - name: WebhooksWebClient
          value: http://docker.internal.localhost:5114
        - name: UseCustomizationData
          value: "True"
        livenessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3          