apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nosqldata-pvc
  namespace: eshop-data
  labels:
    app.kubernetes.io/name: nosqldata-pvc
    app.kubernetes.io/part-of: eshop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
