apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-signalrhub
  namespace: eshop-background
  labels:
    app.kubernetes.io/name: ordering-signalrhub
    app.kubernetes.io/part-of: eshop
    tier: background
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ordering-signalrhub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ordering-signalrhub
        app.kubernetes.io/part-of: eshop
    spec:
      containers:
      - name: ordering-signalrhub
        image: azw7225/ordering-signalrhub:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: EventBusConnection
          value: rabbitmq.eshop-data.svc.cluster.local
        - name: AzureServiceBusEnabled
          value: "False"
        - name: ApplicationInsights__InstrumentationKey
        - name: identityUrl
          value: http://identity-api.eshop-apis.svc.cluster.local
        livenessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3