apiVersion: v1
kind: Service
metadata:
  name: ordering-signalrhub
  namespace: eshop-background
  labels:
    app.kubernetes.io/name: ordering-signalrhub
    app.kubernetes.io/part-of: eshop
    tier: background
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ordering-signalrhub
  ports:
  - name: p80
    port: 80
    targetPort: 80
