apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: eshop-apis
  labels:
    app.kubernetes.io/name: payment-api
    app.kubernetes.io/part-of: eshop
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment-api
        app.kubernetes.io/part-of: eshop
    spec:
      serviceAccountName: eshop-developer
      containers:
      - name: payment-api
        image: azw7225/payment-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: EventBusConnection
          value: rabbitmq.eshop-data.svc.cluster.local
        - name: AzureServiceBusEnabled
          value: "False"
        - name: Serilog__MinimumLevel__Override__payment-api.IntegrationEvents.EventHandling
          value: Verbose
        - name: Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ
          value: Verbose
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5