apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: eshop-data
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: eshop
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/part-of: eshop
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: 5672   
        - containerPort: 15672
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi  