apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: eshop-data
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: eshop
    tier: data
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
  - name: p5672
    port: 5672
    targetPort: 5672
  - name: p15672
    port: 15672
    targetPort: 15672
