apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: eshop-monitoring
  labels:
    app.kubernetes.io/name: seq
    app.kubernetes.io/part-of: eshop
    tier: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: seq
  ports:
  - name: p80
    port: 80
    targetPort: 80
