apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: eshop-monitoring
  labels:
    app.kubernetes.io/name: seq
    app.kubernetes.io/part-of: eshop
    tier: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seq
        app.kubernetes.io/part-of: eshop
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        ports:
        - containerPort: 80
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SEQ_FIRSTRUN_ADMINPASSWORD
          value: Pass@word
        volumeMounts:
        - name: seq-data
          mountPath: /data
      volumes:
      - name: seq-data
        emptyDir: {}  