apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqldata-pvc
  namespace: eshop-data
  labels:
    app.kubernetes.io/name: sqldata-pvc
    app.kubernetes.io/part-of: eshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi