apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldata
  namespace: eshop-data
  labels:
    app.kubernetes.io/name: sqldata
    app.kubernetes.io/part-of: eshop
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sqldata
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sqldata
        app.kubernetes.io/part-of: eshop
    spec:
      containers:
        - name: sqldata
          image: mcr.microsoft.com/mssql/server:2019-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: "Pass@word"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_MEMORY_LIMIT_MB
              value: "3072"   # 3 GiB
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              memory: "4Gi"
          volumeMounts:
            - name: data
              mountPath: /var/opt/mssql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sqldata-pvc
