apiVersion: v1
kind: Service
metadata:
  name: webhooks-api
  namespace: eshop-apis
  labels:
    app.kubernetes.io/name: webhooks-api
    app.kubernetes.io/part-of: eshop
    tier: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: webhooks-api
  ports:
  - name: p80
    port: 80
    targetPort: 80
