apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-client
  namespace: eshop-background
  labels:
    app.kubernetes.io/name: webhooks-client
    app.kubernetes.io/part-of: eshop
    tier: background
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhooks-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webhooks-client
        app.kubernetes.io/part-of: eshop
    spec:
      containers:
      - name: webhooks-client
        image: azw7225/webhook-client:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: Token
          value: 6168DB8D-DC58-4094-AF24-483278923590
        - name: IdentityUrl
          value: http://docker.internal.localhost:5105
        - name: CallBackUrl
          value: http://docker.internal.localhost:5114
        - name: WebhooksUrl
          value: http://webhooks-api
        - name: SelfUrl
          value: http://webhooks-client/
