apiVersion: v1
kind: Service
metadata:
  name: webmvc
  namespace: eshop-frontend
  labels:
    app.kubernetes.io/name: webmvc
    app.kubernetes.io/part-of: eshop
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: webmvc
  ports:
  - name: p80
    port: 80
    targetPort: 80
