apiVersion: apps/v1
kind: Deployment
metadata:
  name: webspa
  namespace: eshop-frontend
  labels:
    app.kubernetes.io/name: webspa
    app.kubernetes.io/part-of: eshop
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webspa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webspa
        app.kubernetes.io/part-of: eshop
    spec:
      serviceAccountName: eshop-frontend-deployer
      containers:
      - name: webspa
        image: azw7225/webspa:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: IdentityUrl
          value: http://docker.internal.localhost:5105
        - name: PurchaseUrl
          value: http://docker.internal.localhost:5202
        - name: IdentityUrlHC
          value: http://identity-api/hc
        - name: UseCustomizationData
          value: "True"
        - name: ApplicationInsights__InstrumentationKey
          value: ""
        - name: OrchestratorType
          value: ""
        - name: SignalrHubUrl
          value: http://docker.internal.localhost:5202
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        # Temporarily disabled for autoscaling demo
        # livenessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
