apiVersion: v1
kind: Service
metadata:
  name: webshoppingagg
  namespace: eshop-gateways
  labels:
    app.kubernetes.io/name: webshoppingagg
    app.kubernetes.io/part-of: eshop
    tier: gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: webshoppingagg
  ports:
  - name: p80
    port: 80
    targetPort: 80
